### PR TITLE
Use slurp macro to read styles from .css file

### LINKED ISSUE #24: Make CSS not inline
~~Possible solutions:~~

- ~~SASS ([plugin](https://github.com/Deraen/sass4clj#leiningen))~~
- ~~Garden~~

This is a prerequisite for #17, because the panel is currently picking up styles from its parent window, so we need to add a CSS-reset, which would be very unwieldy inline (though I suppose it's totally possible).

Edit: We will use clojure macro to read a CSS file (improving the current way, in which we are defining CSS in a string within cljs), and a separate issue is made to introduce CSS preprocessing!

### PR DESCRIPTION
**Pull request by daiyi**
This PR allows introduces a macro to wrap clojure's slurp function, to read CSS from a proper .css file (previously the CSS was defined as a string).

closes #24

### CODE REVIEW

**Comment by daiyi** [comment]
I tried it on the todomvc example project and it seems to be working!

**Comment by daiyi** [comment]
Oh wait, what I actually tried was installing the lastest published version on clojars. How do I install my branch of my local version? (I tried to look it up and the internet told me to use checkouts (??))

**Comment by Dexterminator** [comment]
@daiyi I suggest:
1. `cd` to the re-frame-trace repo, and go your `slurp-css` branch
2. Run `lein install` (which will install your /re-frame-trace/target/trace-0.1.4-SNAPSHOT.jar or something similar into a local repo)
3. Create a new folder, `cd` to it, and clone a fresh todomvc project into it (without creating a checkouts file)
4.  Add the dependency to the todomvc project (I think [day8.re-frame/trace "0.1.4-SNAPSHOT"])
5. Try it out!

Btw, i'm `curlyfry` on the clojurians slack if you wanna discuss anything there (ping @saskali  as well).

**Comment by danielcompton** [comment]
I think this is closed by merging #60.

**Comment by danielcompton** [comment]
I tested this on our project and the CSS came in fine.

**Pull request closed without merging**
