### PR TITLE
Table readability

### PR DESCRIPTION
**Pull request by daiyi**
I wanted to make the traces table more readable, since I spend all day looking at it (:

- pick more calmer colours for the op names (still working on this, I'm still kinda iffy on this palette), and constrain the amount of colour -- the amount of colour felt distracting
- make sure the op name colours are accessible (AA standard)
- nudge the dropdown arrows closer to the op names
- style the trace details to convey more association with the trace that they're describing
- trace names are unlined on hover, to show that clicking on them has an effect

**before**

old table

**after**

new table

### CODE REVIEW

**Comment by danielcompton** [comment]
Hey this all looks pretty cool, I would want to tighten up the spacing between each row. Possibly we can also drop the hairlines between each trace. See Tufte: http://www.darkhorseanalytics.com/blog/data-looks-better-naked

**Comment by daiyi** [comment]
I agree with the hair lines, but I wanted some way to show horizonal coherency, since the columns are spaced really far apart. So I decided to bring back to stripes, but as subtle as possible, and this time without the on-hover stripe (it was really distracting), brightening the dropdown arrow instead. Also, when the details are expanded, the detail row is the same colour as the row of the trace it describes., to show the relationship between the trace and its details.

table with stripes

**Comment by daiyi** [comment]
Search icon for the filter field, and a lil printer icon to indicate that clicking the trace details prints it out \o/

traces table search and print icon update

**Comment by daiyi** [comment]
Making it more obvious that filtering is happening (to avoid the frustration of "where are my traces?? oh right there's a filter), mirroring some designs from chrome devtools. Also, clicking the filter count will reset filtering (remove all filters).

filter state is highlighted

**Comment by daiyi** [comment]
I've been working on this over the weekend because I'm using it in my own project and making little nit fixes as I run into frustrations (:

**Comment by Dexterminator** [comment]
Really liking the changes here!

**Comment by daiyi** [comment]
Any feedback that I should work on? is it ready to go? \o/

**Pull request merged**
